### ISSUE TITLE
node ace make:migration error command not found

### ISSUE THREAD

**Issue by prondubuisi** [ammezie/adonis5-tasks#3]
Hello @ammezie @thetutlage Was going through the tutorial here https://adonismastery.com/courses/adonisjs-5-from-scratch ,
and I tried running the ` node ace make:migration`, but I am  getting an error of command not found, Is there any way I can fix this?

I tried checking for the command and this is what I see 
```
prondubuisi@prondubuisi:~/gitrepos/taskist$ node ace --help

Available commands
  build                 Compile typescript code to Javascript. Optionally watch for file changes
  invoke                Invoke post install instructions on a given AdonisJS package
  serve                 Compile typescript code to Javascript and start the HTTP server

dump
  dump:rcfile           Dump contents of .adonisrc.json file along with defaults

generate
  generate:key          Generate a new APP_KEY secret
  generate:manifest     Generate manifest file to execute ace commands

list
  list:routes           List application routes

make
  make:command          Make a new ace command
  make:controller       Make a new HTTP controller
  make:exception        Make a new exception handle
  make:listener         Make a new event listener class
  make:middleware       Make a new middleware
  make:prldfile         Make a new preloaded file. Preloaded files are loaded automatically on boot
  make:provider         Make a new IoC container provider
  make:validator        Make a new validator
  make:view             Make a new view template

Global Flags
  -h, --help boolean      
  -v, --version boolean 
```  

Thanks for putting together the awesome tutorial!

**Comment by ammezie** [comment]
You have to install and setup lucid.

https://adonismastery.com/courses/adonisjs-5-from-scratch/lessons/setting-up-a-database-adonisjs-5-from-scratch

**Comment by prondubuisi** [comment]
I tried doing that following the guidelines in the video

* npm install @adonisjs/lucid@alpha
* node ace invoke @adonisjs/lucid
* npm install mysql

Is there any change I am supposed to effect manually?

**Comment by ammezie** [comment]
That's all you need. Do make sure you compile/build your code for the changes to take effect.

**Comment by prondubuisi** [comment]
Hello @ammezie works like a charm, had to stop my server and restart using `node ace serve --watch` thanks for the help, wondering if there is any documentation for working with database migrations, seeders etc, with Adonis5 did not see that in the preview docs.

**Comment by ammezie** [comment]
Cool! It is advisable to always have a separate terminal running `node ace serve --watch`. 
Here's the docs: https://preview.adonisjs.com/guides/database/introduction

**Comment by prondubuisi** [comment]
Super thanks.
